### ISSUE TITLE
该项目使用了其他开源项目的代码，根据相应的开源协议应当标注原开发者的版权信息。

### ISSUE THREAD

**Issue by C4a15Wh** [YYRDIO/Kyouka-button#3]
![image](https://user-images.githubusercontent.com/61458603/123209488-3e29cb80-d4f3-11eb-9c10-985bae1311d4.png)
![image](https://user-images.githubusercontent.com/61458603/123209545-5a2d6d00-d4f3-11eb-9dea-913bbc48a2d9.png)
![98{1GPIGQT7CJ9C1V0 83PS](https://user-images.githubusercontent.com/61458603/123209626-7a5d2c00-d4f3-11eb-971d-a8ab214f9095.jpg)
![D)F}WNDI@3Q@_DUT6234}{K](https://user-images.githubusercontent.com/61458603/123209706-95c83700-d4f3-11eb-8416-28b5929f6bb8.jpg)
为什么您在之前的版本中添加过，但在后续的更新里又删除了？
请及时根据GPLv3协议更新版权信息。

**Comment by Timolop233** [comment]
抱歉，给原作者带来麻烦了
因为我不是习惯git 使用的是文件上传
增加完语音后上传连同未更改的readme.md..也一起拖拽上传了
实在对不起，我会注意的
现在已经增加完了
